      FUNCTION DNINEJ(X1,Y1,Z1,X2,Y2,Z2,X3,Y3,Z3)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION XJ9J(200)
      DATA MXDIM/200/
C
      IVAL=MXDIM
      CALL J9J(X1,Y1,  X2,Y2,Z2,X3,Y3,Z3,IVAL,Z1MIN,XJ9J)
      IND=1+NINT(Z1-Z1MIN)
      DNINEJ=0.D0
      IF (IND.GE.1 .AND. IND.LE.IVAL) DNINEJ=XJ9J(IND)
      RETURN
      END
