      FUNCTION DSIXJ(XJ1,XJ2,XJ5,XJ4,XJ3,XJ6)
C
C     CALCULATES 6-J SYMBOL:   _(J1 J2 J3 )_
C                               (J4 J5 J6 )
C     INTERFACE TO J6J ROUTINE.
C     MODIFIED BY S. GREEN 20 AUG 93; PASS DIMENSION OF XJ6J FOR CHECKING
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      PARAMETER (MXDIM=200)
      DIMENSION XJ6J(MXDIM)
      LOGICAL VALID
      VALID(XL1,XL2,XL3)=XL1+XL2+XL3-FLOAT(NINT(XL1+XL2+XL3)).LT.0.1D0
      IVAL=MXDIM
      IF (.NOT.(VALID(XJ1,XJ2,XJ3) .AND. VALID(XJ1,XJ5,XJ6) .AND.
     &          VALID(XJ4,XJ2,XJ6) .AND. VALID(XJ1,XJ2,XJ6))) THEN
        WRITE(6,*) ' *** ERROR ***'
        WRITE(6,*) ' SIXJ ROUTINE HAS BEEN CALLED WITH INVALID',
     1             ' ARGUMENTS'
        WRITE(6,*) XJ1,XJ2,XJ3
        WRITE(6,*) XJ4,XJ5,XJ6
        STOP
      ENDIF
      CALL J6J(XJ2,XJ3,
     1         XJ4,XJ5,XJ6,
     3         IVAL,XJ1MIN,XJ6J)
      IND=1+NINT(XJ1-XJ1MIN)
      DSIXJ=0.D0
      IF (IND.GE.1 .AND. IND.LE.IVAL) DSIXJ=XJ6J(IND)
      RETURN
      END
